#!/usr/bin/perl -w
#
#
# Builds a distribution, including checks using automake and checks
# specific for this package
#

use strict;


# make sure we have an initial makefile

system "./configure";

if ($?)
{
    die "./configure failed";
}


# make sure we remove alien files

system "make distclean";

if ($?)
{
    die "distclean failed";
}


# remake the makefiles

system "./configure --with-delete-operation";

if ($?)
{
    die "./configure failed";
}


# check the complete distribution

system "make distcheck";

if ($?)
{
    die "distcheck failed";
}


# remove the distribution

#! this is supposed to remove a distribution with possibly files that
#! are leftover from running the tests.  For some reason automake does
#! not detect this discrepancy.

system "make clean";

if ($?)
{
    die "clean failed";
}


# # generate html for the test cases

# #! should be put in Makefile.am, but breaks distcheck.
# #! this one breaks the distcheck, because automake makes dist dirs read-only

# system "cd tests && ./tests_2_html";

# if ($?)
# {
#     die "generating html for the test cases failed";
# }


# recreate the distribution

system "make dist";

if ($?)
{
    die "dist failed";
}


# rebuild and test the distribution

system "./test-dist";

if ($?)
{
    die "./test-dist failed";
}


# # update the website

# system "make html-upload";

# if ($?)
# {
#     die "make html-upload failed";
# }


