#!/usr/bin/perl -w
#
#
# Get the current distribution from sourceforge and check its
# validity.
#

use strict;

system 'mkdir --parents "/tmp/neurospaces"';

chdir '/tmp/neurospaces' || die "Cannot cd to /tmp/neurospaces";


{
    # $Format: "system 'wget \"http://superb-west.dl.sourceforge.net/sourceforge/neurospaces/${package}-${label}.tar.gz\"';"$
system 'wget "http://superb-west.dl.sourceforge.net/sourceforge/neurospaces/model-container-python-4.tar.gz"';
}

if ($?)
{
    die "wget failed";
}


{
    # $Format: "system 'tar vxfz \"${package}-${label}.tar.gz\"';"$
system 'tar vxfz "model-container-python-4.tar.gz"';
}

if ($?)
{
    die "tar failed";
}


{
    # $Format: "chdir '${package}-${label}' || die 'chdir failed';"$
chdir 'model-container-python-4' || die 'chdir failed';
}


{
    # $Format: "system './configure';"$
system './configure';
}

if ($?)
{
    die "./configure failed";
}


{
    # $Format: "system 'make';"$
system 'make';
}

if ($?)
{
    die "make failed";
}


{
    # $Format: "system 'make check';"$
system 'make check';
}

if ($?)
{
    die "make check failed";
}


