#!/usr/bin/perl -w
#
#
# build script to be used to unpack and test a dist tarball.
#
# builds in /tmp/neurospaces/<whatever>, and runs the tests.
#

use strict;


{
    # $Format: "system 'mkdir --parents \"/tmp/neurospaces/${package}-${label}\"';"$
system 'mkdir --parents "/tmp/neurospaces/neurospacesread-des-8"';
}

if ($?)
{
    die "mkdir failed";
}


{
    # $Format: "system \"cp '/local_home/local_home/hugo/neurospaces_project/neurospaces/source/c/snapshots/0/${package}-${label}.tar.gz' '/tmp/neurospaces/${package}-${label}'\";"$
system "cp '/local_home/local_home/hugo/neurospaces_project/neurospaces/source/c/snapshots/0/neurospacesread-des-8.tar.gz' '/tmp/neurospaces/neurospacesread-des-8'";
}

if ($?)
{
    die "cp failed";
}


{
    # $Format: "chdir \"/tmp/neurospaces/${package}-${label}\";"$
chdir "/tmp/neurospaces/neurospacesread-des-8";
}

if ($?)
{
    die "chdir failed";
}


{
    # $Format: "system \"tar xfz '${package}-${label}.tar.gz'\";"$
system "tar xfz 'neurospacesread-des-8.tar.gz'";
}

if ($?)
{
    die "cp failed";
}


{
    # $Format: "chdir \"${package}-${label}\";"$
chdir "neurospacesread-des-8";
}

if ($?)
{
    die "chdir failed";
}


{
    # $Format: "system \"./configure\";"$
system "./configure";
}

if ($?)
{
    die "configure failed";
}


{
    # $Format: "system 'make';"$
system 'make';
}

if ($?)
{
    die "make failed";
}


{
    # $Format: "system 'make test';"$
system 'make test';
}

if ($?)
{
    die "test failed";
}

